const ElectronicsData = [
    {
        "id": "1",
        "ProductImage": "https://i.gadgets360cdn.com/large/realme_gt_neo_6_se_weibo_1712667857810.jpg?downsize=950:*",
        "Title": "Realme GT 6T 5G",
        "Rating": "4.6",
        "Offer": "₹35,999",
        "Price": "₹37,999",
        "Discount": "5% Off",
        "Description": " India's 1st 7+ Gen 3 Flagship Chipset | 1.5M + AnTuTu Score | 5500mAh+120W | The World's Brightest Flagship Display"
    },
    {
        "id": "2",
        "ProductImage": "https://m.media-amazon.com/images/I/61OTjbC7z5L._SX679_.jpg",
        "Title": "Apple Watch SE",
        "Rating": "4.3",
        "Offer": "₹24,999",
        "Price": "₹29,900",
        "Discount": "16% Off",
        "Description": "(2nd Gen, 2023) Smartwatch with Starlight Aluminum Case with Starlight Sport Band S/M. Fitness & Sleep Tracker, Crash Detection, Heart Rate Monitor, Retina Display",  
    },
    {
        "id": "3",
        "ProductImage": "https://m.media-amazon.com/images/I/41rSkgtyYKL._SX300_SY300_QL70_FMwebp_.jpg",
        "Title": "Boult Audio BassBuds",
        "Rating": "4.0",
        "Offer": "₹349",
        "Price": "₹999",
        "Discount": "65% Off",
        "Description": "X1 in-Ear Wired Earphones with 10mm Extra Bass Driver and HD Sound with mic(Blue)",  
    },
    {
        "id": "4",
        "ProductImage": "https://m.media-amazon.com/images/I/61YeU68eqGL._SX679_.jpg",
        "Title": "HP Pen Drive",
        "Rating": "4.3",
        "Offer": "₹549",
        "Price": "₹915",
        "Discount": "40% Off",
        "Description": "HP 712w 32GB USB 3.2 Flash Drive- Blue",  
    },
    {
        "id": "5",
        "ProductImage": "https://m.media-amazon.com/images/I/51lX5oZbtQL._SY450_.jpg",
        "Title": "Amazon Fire TV Stick ",
        "Rating": "4.3",
        "Offer": "₹2,799",
        "Price": "₹4,999",
        "Discount": "44% Off",
        "Description": "Amazon Fire TV Stick with Alexa Voice Remote (includes TV and app controls) | HD streaming device",  
    },
    {
        "id": "6",
        "ProductImage": "https://m.media-amazon.com/images/I/51Yx1TsWZyL._SX522_.jpg",
        "Title": "OnePlus Nord Buds 2r ",
        "Rating": "4.2",
        "Offer": "₹1,794",
        "Price": "₹2,229",
        "Discount": "22% Off",
        "Description": " True Wireless in Ear Earbuds with Mic, 12.4mm Drivers, Playback:Upto 38hr case,4-Mic Design, IP55 Rating [ Misty Grey ]",  
    },
    {
        "id": "7",
        "ProductImage": "https://m.media-amazon.com/images/I/81tmCrtiRgL._SX679_.jpg",
        "Title": "Lenovo LOQ",
        "Rating": "3.9",
        "Offer": "₹69,990",
        "Price": "₹95,890",
        "Discount": "27% Off",
        "Description": "Intel Core i5-12450HX /39.6cm/ 144Hz 300Nits FHD Gaming Laptop (16GB/512GB SSD/Win 11/ RTX 3050 6GB Graphics/100% sRGB/MSO 21/3 Mon Game Pass/Grey/2.4Kg), 83GS003UIN",  
    },
    {
        "id": "8",
        "ProductImage": "https://m.media-amazon.com/images/I/61wsvCGXqnL._SX679_.jpg",
        "Title": "GoPro HERO 12",
        "Rating": "4.3",
        "Offer": "₹38,990",
        "Price": "₹45,000",
        "Discount": "13% Off",
        "Description": "Waterproof Action Camera with Front & Rear LCD Screens, 5.3K60 Ultra HD Video, HyperSmooth 6.0 + AutoBoost, Live Streaming with Enduro Battery",  
    },
    {
        "id": "9",
        "ProductImage": "https://m.media-amazon.com/images/I/71+6UG0Ce6L._SX679_.jpg",
        "Title": "Acer ED270R S3 ",
        "Rating": "4.1",
        "Offer": "₹12,699",
        "Price": "₹15,299",
        "Discount": "17% Off",
        "Description": "27 Inch (68.58 Cm) Full HD 1500 R Curved Gaming LCD Monitor with LED Back Light I 1MS VRB, 180Hz Refresh Rate I AMD Freesync Premium I 2 x HDMI 1 x Display Port I HDR 10 I Black",  
    },
    {
        "id": "10",
        "ProductImage": "https://m.media-amazon.com/images/I/61V6TNPfT4L._SX679_.jpg",
        "Title": "Ant Esports Gaming Keyboard ",
        "Rating": "3.9",
        "Offer": "₹1,599",
        "Price": "₹4,999",
        "Discount": "68% Off",
        "Description": "Ant Esports Gaming Keyboard MK1000 TKL Mechanical Multicolor LED Backlit Wired -Black with Outemu Blue Switch",  
    },

]
export default ElectronicsData